fix(types): clean up `canonical-json` types in ambient.d.ts
mojaloop/thirdparty-api-adapter pull request #27
Opened 2020-09-11 04:13 UTC by lewisdaly

2020-09-11 04:23 UTC, kleyow approved these changes

2020-09-11 07:41 UTC, eoln requested changes
small change: better use unknown instead of any

2020-09-11 07:41 UTC, eoln commented on ambient.d.ts
> +  export default function stringify(value: any, replacer?: ReplacerFunc, space?: string | number): string
```suggestion
  export default function stringify(value: unknown, replacer?: ReplacerFunc, space?: string | number): string
```

2020-09-11 07:47 UTC, lewisdaly commented on ambient.d.ts
> +  export default function stringify(value: any, replacer?: ReplacerFunc, space?: string | number): string
oops! missed that one

2020-09-14 06:45 UTC, eoln approved these changes
lgtm

2020-09-14 07:01 UTC, merged